# 推送代码到 vercel  更新 ctool.dev
name: push-vercel
on:
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: merge master to vercel branch
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ github.token }}
          from_branch: master
          to_branch: vercel


